//
// Generated file, do not edit! Created by nedtool 5.0 from ConsumerRequest.msg.
//

#ifndef __CONSUMERREQUEST_M_H
#define __CONSUMERREQUEST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ConsumerRequest.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message ConsumerRequest
 * {
 *     int consumerID;
 *     simtime_t sentTimestamp;
 * }
 * </pre>
 */
class ConsumerRequest : public ::omnetpp::cMessage
{
  protected:
    int consumerID;
    ::omnetpp::simtime_t sentTimestamp;

  private:
    void copy(const ConsumerRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ConsumerRequest&);

  public:
    ConsumerRequest(const char *name=nullptr, int kind=0);
    ConsumerRequest(const ConsumerRequest& other);
    virtual ~ConsumerRequest();
    ConsumerRequest& operator=(const ConsumerRequest& other);
    virtual ConsumerRequest *dup() const {return new ConsumerRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getConsumerID() const;
    virtual void setConsumerID(int consumerID);
    virtual ::omnetpp::simtime_t getSentTimestamp() const;
    virtual void setSentTimestamp(::omnetpp::simtime_t sentTimestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ConsumerRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ConsumerRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CONSUMERREQUEST_M_H

